version: '2'
services:
  cache:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - logvolume01:/var/log
    links:
    - postgres
  postgres:
    image: postgres
volumes:
  logvolume01: {}
